load("utils.bzl", "gen_evm_test", "gen_scheme_test")

load("@rules_python//python:defs.bzl", "py_library")

gen_evm_test("core/addr")
gen_evm_test("core/base")
gen_evm_test("core/enums")
gen_evm_test("fastw3_goerli")
gen_evm_test("fastw3_ethereum")
gen_evm_test("fastw3_arbitrum")
gen_scheme_test("test0")